# Generated by Django 4.2.2 on 2023-10-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulolicitacion',
            name='Descripcion',
        ),
        migrations.AlterField(
            model_name='articulousodiario',
            name='utilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.utilidad'),
        ),
    ]
