# Generated by Django 4.2.2 on 2023-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_utilidad_remove_articulolicitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientolicitacion',
            name='Ubicacion',
            field=models.CharField(default='cambiar', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientousodiario',
            name='Ubicacion',
            field=models.CharField(default='cambiar', max_length=30),
            preserve_default=False,
        ),
    ]
