# Generated by Django 4.2.2 on 2023-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_movimientolicitacion_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientolicitacion',
            name='NumeroOrden',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
