# Generated by Django 4.2.2 on 2023-10-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_rename_numeroorden_movimientolicitacion_numero_de_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulolicitacion',
            name='IdCategorias',
        ),
        migrations.RemoveField(
            model_name='articulolicitacion',
            name='IdUbicacion',
        ),
        migrations.RemoveField(
            model_name='articulolicitacion',
            name='licitacion',
        ),
        migrations.RemoveField(
            model_name='articulousodiario',
            name='IdCategorias',
        ),
        migrations.RemoveField(
            model_name='articulousodiario',
            name='IdUbicacion',
        ),
        migrations.RemoveField(
            model_name='articulousodiario',
            name='utilidad',
        ),
        migrations.DeleteModel(
            name='MovimientoLicitacion',
        ),
        migrations.DeleteModel(
            name='MovimientoUsoDiario',
        ),
        migrations.DeleteModel(
            name='ArticuloLicitacion',
        ),
        migrations.DeleteModel(
            name='ArticuloUsoDiario',
        ),
        migrations.DeleteModel(
            name='Licitacion',
        ),
        migrations.DeleteModel(
            name='Utilidad',
        ),
    ]
