# Generated by Django 4.2.2 on 2023-10-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_remove_articulolicitacion_idcategorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('codigo_folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=30)),
                ('articulo_licitacion', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('Licitacion', models.CharField(max_length=40)),
                ('Cantidad', models.IntegerField()),
                ('Destino', models.CharField(max_length=30)),
                ('Numero_de_Orden', models.CharField(max_length=30)),
                ('Ubicacion', models.CharField(max_length=30)),
                ('Entrega_conforme', models.CharField(max_length=30)),
                ('Recibe_conforme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoUsoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('Nombre_de_Articulo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('Codigo', models.CharField(max_length=30)),
                ('Destino', models.CharField(max_length=30)),
                ('accion', models.CharField(max_length=30)),
                ('Cantidad', models.IntegerField()),
                ('Ubicacion', models.CharField(max_length=30)),
                ('Entrega_conforme', models.CharField(max_length=30)),
                ('Recibe_conforme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloUsoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Existencias', models.IntegerField()),
                ('saldo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdCategorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.categorias')),
                ('IdUbicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ubicacion')),
                ('utilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.utilidad')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('Existencias', models.IntegerField()),
                ('saldo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdCategorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.categorias')),
                ('IdUbicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ubicacion')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.licitacion')),
            ],
        ),
    ]
