# Generated by Django 4.2.2 on 2023-07-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Herramientas', '0002_remove_herramientas_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('Funcion', models.CharField(max_length=20)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Acta_entrega_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Destino', models.CharField(max_length=25)),
                ('Recibe', models.CharField(max_length=25)),
                ('Entrega', models.CharField(max_length=25)),
                ('Herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herramientas.herramientas')),
            ],
        ),
    ]
