# Generated by Django 4.2.2 on 2023-09-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Herramientas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta_entrega_herramienta',
            name='Herramienta',
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Herramientas.acta_entrega_herramienta')),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Herramientas.herramientas')),
            ],
        ),
        migrations.AddField(
            model_name='acta_entrega_herramienta',
            name='Herramienta',
            field=models.ManyToManyField(blank=True, through='Herramientas.Prestamo', to='Herramientas.herramientas'),
        ),
    ]
