# Generated by Django 4.2.2 on 2023-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Herramientas', '0004_remove_acta_entrega_herramienta_herramienta_prestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad',
        ),
    ]
