# Generated by Django 4.2.2 on 2023-10-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Herramientas', '0007_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
